const commonAmenities = [
    "Free Wifi",
    "Free Parking",
    "Pool",
    "Gym",
    "Kitchen",
    "TV",
    "AC",
    "Sea Views",
    "Garden",
    "Antique Furnishings",
    "Ski-in/Ski-out",
    "Fireplace",
    "Mountain Views",
    "Outdoor Lounge",
    "Traditional Decor",
    "Peaceful Surroundings",
    "Central Location",
    "Rooftop Terrace",
    "Sunset Views",
    "Artistic Decor",
    "Modern Decor",
    "City Views",
    "Coffee Maker",
    "Hot Tub",
    "Historic Neighborhood",
    "Close to Public Transit",
    "Lakefront",
    "Pet Friendly",
    "Private Beach",
    "Private Elevator",
    "Luxury Decor",
    "Movie Theater",
    "Game Room",
    "Wine Cellar",
    "BBQ Grill",
];

export default commonAmenities;